// PROTOTYPE — throwaway fake data. No backend, no persistence.
import type { Account, Session, Stats } from './types'

export const now = Date.now()
const min = 60_000
const hr = 3_600_000

export const account: Account = {
  billingMode: 'subscription',
  plan: 'Max 20×',
  fiveHour: { usedPct: 62, resetsAt: now + hr + 40 * min },
  sevenDay: { usedPct: 41, resetsAt: now + 3 * 24 * hr + 5 * hr },
}

export const sessions: Session[] = [
  {
    id: 'a3e8fb0b',
    title: 'Prototype the code-by-wire UI',
    project: 'code-by-wire',
    branch: 'main',
    state: 'working',
    management: 'managed',
    model: 'claude-opus-4-8',
    contextPct: 47,
    contextWindow: 200_000,
    contextBreakdown: { system: 18_000, tools: 12_400, messages: 58_000, files: 5_600 },
    usage: { inputTokens: 41_000, outputTokens: 88_500, cacheReadTokens: 6_240_000, cacheCreationTokens: 410_000 },
    equivApiValueUsd: 6.42,
    lastActivityMs: now - 4 * 1000,
    currentTask: 'Build the three Overview variants',
    tasks: [
      { id: 't1', subject: 'Scaffold Vite + React + Tailwind', status: 'completed' },
      { id: 't2', subject: 'Normalized types + mock data', status: 'completed' },
      { id: 't3', subject: 'Build the three Overview variants', status: 'in_progress' },
      { id: 't4', subject: 'Workspace drill-down', status: 'blocked', blockedBy: ['t3'] },
      { id: 't5', subject: 'Floating variant switcher', status: 'pending', blockedBy: ['t2'] },
    ],
    subagents: [
      { id: 's1', type: 'Explore', status: 'done', model: 'claude-opus-4-8', tokens: 93_247, durationMs: 175_489 },
      { id: 's2', type: 'Explore', status: 'done', model: 'claude-opus-4-8', tokens: 78_120, durationMs: 160_220 },
      { id: 's3', type: 'claude-code-guide', status: 'done', model: 'claude-opus-4-8', tokens: 93_247, durationMs: 175_489 },
    ],
  },
  {
    id: '724b3f00',
    title: 'Release cut: force-push the tag',
    project: 'Transporty',
    branch: 'main',
    state: 'waiting',
    management: 'observed',
    model: 'claude-opus-4-8',
    contextPct: 71,
    contextWindow: 200_000,
    contextBreakdown: { system: 16_500, tools: 9_800, messages: 109_000, files: 6_700 },
    usage: { inputTokens: 22_400, outputTokens: 51_900, cacheReadTokens: 8_900_000, cacheCreationTokens: 520_000 },
    equivApiValueUsd: 9.18,
    lastActivityMs: now - 70 * 1000,
    waitingReason: 'Permission — Bash: git push --force-with-lease origin main',
    tasks: [
      { id: 'r1', subject: 'Bump version + changelog', status: 'completed' },
      { id: 'r2', subject: 'Tag release', status: 'in_progress' },
      { id: 'r3', subject: 'Push tag to origin', status: 'pending', blockedBy: ['r2'] },
    ],
    subagents: [],
  },
  {
    id: '1f9c2d77',
    title: 'Checkout refactor: choose migration strategy',
    project: 'cxss-web',
    branch: 'feat/checkout',
    state: 'waiting',
    management: 'managed',
    model: 'claude-sonnet-4-6',
    contextPct: 34,
    contextWindow: 200_000,
    contextBreakdown: { system: 15_000, tools: 8_200, messages: 39_000, files: 6_000 },
    usage: { inputTokens: 18_900, outputTokens: 34_200, cacheReadTokens: 2_100_000, cacheCreationTokens: 180_000 },
    equivApiValueUsd: 1.94,
    lastActivityMs: now - 3 * min,
    waitingReason: 'AskUserQuestion — Migration strategy: expand-contract vs big-bang?',
    tasks: [
      { id: 'c1', subject: 'Audit current checkout schema', status: 'completed' },
      { id: 'c2', subject: 'Decide migration strategy', status: 'in_progress' },
    ],
    subagents: [
      { id: 'cs1', type: 'Explore', status: 'done', model: 'claude-haiku-4-5', tokens: 14_900, durationMs: 41_000 },
    ],
  },
  {
    id: 'b2e7a910',
    title: 'Harden the rate-limit middleware',
    project: 'Transporty',
    branch: 'api-rate-limits',
    state: 'working',
    management: 'observed',
    model: 'claude-sonnet-4-6',
    contextPct: 88,
    contextWindow: 200_000,
    contextBreakdown: { system: 16_000, tools: 9_000, messages: 142_000, files: 9_000 },
    usage: { inputTokens: 31_500, outputTokens: 62_800, cacheReadTokens: 5_400_000, cacheCreationTokens: 300_000 },
    equivApiValueUsd: 4.07,
    lastActivityMs: now - 11 * 1000,
    currentTask: 'Running test suite — 142 / 210 passing',
    tasks: [
      { id: 'b1', subject: 'Add token-bucket limiter', status: 'completed' },
      { id: 'b2', subject: 'Wire limiter into router', status: 'completed' },
      { id: 'b3', subject: 'Green the test suite', status: 'in_progress' },
    ],
    subagents: [
      { id: 'bs1', type: 'general-purpose', status: 'done', model: 'claude-sonnet-4-6', tokens: 38_400, durationMs: 88_000 },
    ],
  },
  {
    id: 'c4419fe2',
    title: 'Migrate VPC subnets to a reusable module',
    project: 'infra',
    branch: 'tf-network-migration',
    state: 'working',
    management: 'observed',
    model: 'claude-opus-4-8',
    contextPct: 64,
    contextWindow: 1_000_000,
    contextBreakdown: { system: 22_000, tools: 31_000, messages: 540_000, files: 47_000 },
    usage: { inputTokens: 96_000, outputTokens: 210_400, cacheReadTokens: 18_700_000, cacheCreationTokens: 1_240_000 },
    equivApiValueUsd: 21.6,
    lastActivityMs: now - 2 * 1000,
    currentTask: 'Rewriting network module, reviewing the diff',
    tasks: [
      { id: 'i1', subject: 'Inventory existing subnets', status: 'completed' },
      { id: 'i2', subject: 'Author reusable module', status: 'in_progress' },
      { id: 'i3', subject: 'Migrate staging', status: 'pending', blockedBy: ['i2'] },
      { id: 'i4', subject: 'Migrate prod', status: 'pending', blockedBy: ['i3'] },
    ],
    subagents: [
      {
        id: 'is1', type: 'general-purpose', status: 'done', model: 'claude-sonnet-4-6', tokens: 45_200, durationMs: 90_400,
        children: [
          { id: 'is1a', type: 'Explore', status: 'done', model: 'claude-haiku-4-5', tokens: 12_100, durationMs: 28_900 },
        ],
      },
      {
        id: 'is2', type: 'general-purpose', status: 'working', model: 'claude-opus-4-8', tokens: 120_300, durationMs: 212_000,
        children: [
          { id: 'is2a', type: 'code-reviewer', status: 'working', model: 'claude-opus-4-8', tokens: 41_900, durationMs: 96_000 },
        ],
      },
      { id: 'is3', type: 'Explore', status: 'done', model: 'claude-haiku-4-5', tokens: 9_800, durationMs: 22_400 },
    ],
  },
  {
    id: 'd71008aa',
    title: 'Tidy zsh aliases and prompt',
    project: 'dotfiles',
    branch: 'main',
    state: 'idle',
    management: 'managed',
    model: 'claude-haiku-4-5',
    contextPct: 12,
    contextWindow: 200_000,
    contextBreakdown: { system: 11_000, tools: 4_000, messages: 8_000, files: 1_000 },
    usage: { inputTokens: 6_200, outputTokens: 9_400, cacheReadTokens: 410_000, cacheCreationTokens: 38_000 },
    equivApiValueUsd: 0.21,
    lastActivityMs: now - 6 * min,
    currentTask: 'Done — tidied aliases, awaiting next prompt',
    tasks: [{ id: 'd1', subject: 'Consolidate git aliases', status: 'completed' }],
    subagents: [],
  },
  {
    id: 'e9920b14',
    title: 'Draft the README and architecture notes',
    project: 'code-by-wire',
    branch: 'docs',
    state: 'idle',
    management: 'observed',
    model: 'claude-opus-4-8',
    contextPct: 23,
    contextWindow: 200_000,
    contextBreakdown: { system: 17_000, tools: 6_000, messages: 21_000, files: 2_000 },
    usage: { inputTokens: 9_800, outputTokens: 18_700, cacheReadTokens: 980_000, cacheCreationTokens: 76_000 },
    equivApiValueUsd: 1.12,
    lastActivityMs: now - 18 * min,
    currentTask: 'Done — drafted ADR summaries',
    tasks: [],
    subagents: [],
  },
  {
    id: 'f0034c8d',
    title: 'Redesign the marketing hero',
    project: 'marketing-site',
    branch: 'main',
    state: 'ended',
    management: 'observed',
    model: 'claude-sonnet-4-6',
    contextPct: 0,
    contextWindow: 200_000,
    contextBreakdown: { system: 0, tools: 0, messages: 0, files: 0 },
    usage: { inputTokens: 14_200, outputTokens: 28_900, cacheReadTokens: 1_800_000, cacheCreationTokens: 120_000 },
    equivApiValueUsd: 1.78,
    lastActivityMs: now - 2 * hr,
    currentTask: 'Shipped — hero redesign merged',
    tasks: [],
    subagents: [],
  },
  {
    id: '0a5512b9',
    title: 'Scratch: poke at a regex',
    project: 'scratch',
    branch: 'main',
    state: 'ended',
    management: 'managed',
    model: 'claude-haiku-4-5',
    contextPct: 0,
    contextWindow: 200_000,
    contextBreakdown: { system: 0, tools: 0, messages: 0, files: 0 },
    usage: { inputTokens: 2_100, outputTokens: 3_400, cacheReadTokens: 90_000, cacheCreationTokens: 12_000 },
    equivApiValueUsd: 0.07,
    lastActivityMs: now - 5 * hr,
    tasks: [],
    subagents: [],
  },
]

export const stats: Stats = {
  weeklyMessages: [
    { day: 'Mon', count: 2054 },
    { day: 'Tue', count: 3427 },
    { day: 'Wed', count: 3808 },
    { day: 'Thu', count: 3539 },
    { day: 'Fri', count: 3537 },
    { day: 'Sat', count: 2301 },
    { day: 'Sun', count: 4433 },
  ],
  modelMix: [
    { model: 'claude-opus-4-8', tokens: 63_000_000 },
    { model: 'claude-sonnet-4-6', tokens: 11_200_000 },
    { model: 'claude-haiku-4-5', tokens: 1_900_000 },
  ],
  projectRollup: [
    { project: 'infra', sessions: 6, equivUsd: 142.4 },
    { project: 'Transporty', sessions: 14, equivUsd: 98.2 },
    { project: 'code-by-wire', sessions: 9, equivUsd: 41.7 },
    { project: 'cxss-web', sessions: 7, equivUsd: 33.5 },
    { project: 'dotfiles', sessions: 3, equivUsd: 4.1 },
  ],
  weekEquivUsd: 319.9,
  weekTokens: 76_100_000,
}
