/**
 * The curated icon name set, kept in a JSX-free module so the type can be imported from the node
 * program (e.g. the Vitest tests, which `tsconfig.node.json` covers without the `jsx` option) without
 * dragging icons.tsx's JSX into a tsconfig that can't parse it. icons.tsx maps each name to a lucide
 * glyph and is checked against this union via `satisfies Record<IconName, LucideIcon>`, so the two
 * can never drift: add a name here without a glyph there (or vice versa) and the typecheck fails.
 */
export type IconName =
  | "activity"
  | "archive"
  | "arrow-up-right"
  | "bot"
  | "chart-column"
  | "check"
  | "chevron-down"
  | "chevron-right"
  | "chevron-up"
  | "chevrons-down-up"
  | "chevrons-up-down"
  | "circle-user"
  | "clock"
  | "code"
  | "coffee"
  | "coins"
  | "copy"
  | "database"
  | "ellipsis"
  | "eye"
  | "eye-off"
  | "filter"
  | "folder"
  | "folder-open"
  | "gauge"
  | "github"
  | "git-branch"
  | "git-pull-request-arrow"
  | "globe"
  | "id-card"
  | "info"
  | "loader-circle"
  | "monitor"
  | "moon"
  | "palette"
  | "panel-left"
  | "panel-left-close"
  | "panel-left-open"
  | "panel-right"
  | "panel-right-close"
  | "panel-right-open"
  | "pause"
  | "pencil"
  | "pin"
  | "pin-off"
  | "plus"
  | "rocket"
  | "rotate-ccw"
  | "scroll-text"
  | "search"
  | "settings"
  | "sparkles"
  | "square"
  | "square-code"
  | "square-dashed-mouse-pointer"
  | "square-terminal"
  | "sun"
  | "terminal"
  | "timer"
  | "triangle-alert"
  | "worktree"
  | "x";
